let wasm = null;
let canvas = document.getElementById('canvas');
let selLabel = document.getElementById('selLabel');

let cameraYaw = 225 * Math.PI/180;
let cameraPitch = 30 * Math.PI/180;
let cameraZoom = 1.0;

let isDragging = false;
let lastX = 0, lastY = 0;

// Load WASM module generated by Emscripten (room.js + room.wasm)
import createRoomModule from '../build/room.js';

async function init() {
  // Pass canvas to the Emscripten module so it can locate it; module also
  // creates its WebGL context via emscripten_webgl_create_context("#canvas").
  wasm = await createRoomModule({
    canvas: canvas,
    locateFile: (path) => {
      if (path.endsWith('.wasm')) return '../build/room.wasm';
      return path;
    }
  });

  function snap32(v){ return Math.max(32, Math.floor(v/32)*32); }
  function setCanvasSize() {
    // Tiles divisible by 32 + never blurred:
    // - snap CSS size to 32
    // - snap buffer size to 32
    // - use integer DPR scaling without fractional blur, round DPR
    // - pixelated via CSS image-rendering
    const dpr = Math.max(1, Math.round(window.devicePixelRatio || 1));
    const rawW = window.innerWidth;
    const rawH = window.innerHeight;
    const cssW = snap32(rawW);
    const cssH = snap32(rawH);
    const bufW = snap32(cssW * dpr);
    const bufH = snap32(cssH * dpr);
    canvas.width = bufW;
    canvas.height = bufH;
    canvas.style.width = cssW + 'px';
    canvas.style.height = cssH + 'px';
    // ensure WebGL viewport matches buffer
    return { w: bufW, h: bufH, cssW, cssH };
  }

  function resize() {
    const { w, h } = setCanvasSize();
    if (wasm._resize) wasm._resize(w, h);
  }

  // Size canvas BEFORE creating the WebGL context
  const { w: initW, h: initH } = setCanvasSize();
  if (wasm._initialize) wasm._initialize(initW, initH);

  window.addEventListener('resize', resize);

  // Main loop
  function frame() {
    if (wasm._render) wasm._render();
    updateLabel();
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);

  setupInteraction();
  updateLabel();
}

function ndcFromEvent(e) {
  const rect = canvas.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;
  const w = rect.width;
  const h = rect.height;
  const ndcX = (x / w) * 2 - 1;
  const ndcY = 1 - (y / h) * 2;
  return {ndcX, ndcY, x, y, w, h};
}

function setupInteraction() {
  canvas.addEventListener('click', (e) => {
    if (isDragging) return; // avoid click after drag
    const { ndcX, ndcY } = ndcFromEvent(e);
    if (wasm._pickTile) wasm._pickTile(ndcX, ndcY);
  });

  canvas.addEventListener('mousedown', e => {
    isDragging = false;
    lastX = e.clientX; lastY = e.clientY;
    canvas.style.cursor = 'grabbing';
  });
  window.addEventListener('mousemove', e => {
    if (e.buttons !== 1) return;
    const dx = e.clientX - lastX;
    const dy = e.clientY - lastY;
    if (Math.abs(dx)>2 || Math.abs(dy)>2) isDragging = true;
    if (isDragging) {
      cameraYaw -= dx * 0.005;
      cameraPitch += dy * 0.005;
      cameraPitch = Math.max(0.2, Math.min(1.2, cameraPitch));
      if (wasm._setCamera) wasm._setCamera(cameraYaw, cameraPitch, cameraZoom);
    }
    lastX = e.clientX; lastY = e.clientY;
  });
  window.addEventListener('mouseup', () => {
    canvas.style.cursor = 'default';
    setTimeout(()=> isDragging=false, 100);
  });

  canvas.addEventListener('wheel', e => {
    e.preventDefault();
    const delta = -e.deltaY * 0.001;
    cameraZoom = Math.max(0.5, Math.min(2.5, cameraZoom + delta));
    if (wasm._setCamera) wasm._setCamera(cameraYaw, cameraPitch, cameraZoom);
  }, {passive:false});

  // Touch
  let lastTouchX=0,lastTouchY=0;
  canvas.addEventListener('touchstart', e=>{
    const t=e.touches[0]; lastTouchX=t.clientX; lastTouchY=t.clientY;
  }, {passive:true});
  canvas.addEventListener('touchmove', e=>{
    e.preventDefault();
    const t=e.touches[0];
    const dx=t.clientX-lastTouchX, dy=t.clientY-lastTouchY;
    cameraYaw -= dx*0.005;
    cameraPitch += dy*0.005;
    cameraPitch=Math.max(0.2,Math.min(1.2,cameraPitch));
    if(wasm._setCamera) wasm._setCamera(cameraYaw,cameraPitch,cameraZoom);
    lastTouchX=t.clientX; lastTouchY=t.clientY;
  }, {passive:false});
  canvas.addEventListener('touchend', e=>{
    if(e.changedTouches.length===1 && e.touches.length===0){
      const t=e.changedTouches[0];
      const rect=canvas.getBoundingClientRect();
      const x=t.clientX-rect.left, y=t.clientY-rect.top;
      const ndcX=(x/rect.width)*2-1, ndcY=1-(y/rect.height)*2;
      if(wasm._pickTile) wasm._pickTile(ndcX,ndcY);
    }
  });

  window.addEventListener('keydown', e=>{
    let x = wasm._getSelectedX ? wasm._getSelectedX() : 0;
    let y = wasm._getSelectedY ? wasm._getSelectedY() : 0;
    let moved=false;
    if(e.key==='ArrowUp' || e.key==='w' || e.key==='W'){ y+=1; moved=true; }
    if(e.key==='ArrowDown' || e.key==='s' || e.key==='S'){ y-=1; moved=true; }
    if(e.key==='ArrowLeft' || e.key==='a' || e.key==='A'){ x-=1; moved=true; }
    if(e.key==='ArrowRight' || e.key==='d' || e.key==='D'){ x+=1; moved=true; }
    if(moved){
      e.preventDefault();
      if(wasm._selectTile) wasm._selectTile(x,y);
    }
  });

  document.getElementById('resetView').addEventListener('click', ()=>{
    cameraYaw = 225*Math.PI/180;
    cameraPitch=30*Math.PI/180;
    cameraZoom=1.0;
    if(wasm._setCamera) wasm._setCamera(cameraYaw,cameraPitch,cameraZoom);
  });
}

function updateLabel(){
  if(!wasm || !wasm._getSelectedX) return;
  const x=wasm._getSelectedX();
  const y=wasm._getSelectedY();
  selLabel.textContent = `Selected: (${x}, ${y})`;
}

init().catch(err=>{
  console.error(err);
  document.body.innerHTML='<pre style="color:red;padding:20px">'+err.stack+'</pre>';
});
